### ISSUE TITLE
How to remove box-shadow?

### ISSUE THREAD

**Issue by stevespringett** [s4l1h/vue-toastr#47]
Any idea how can I remove the box-shadow from all toasts? I haven't been able to figure that out.

**Comment by s4l1h** [comment]
If you write this css code somewhere. The box-shadow will be gone.
```css
.toast-container>div{
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}
```
