### ISSUE TITLE
How do I add a close icon to prompt the user to manually close

### ISSUE THREAD

**Issue by anjayluh** [s4l1h/vue-toastr#48]
I want to add an icon(X) in the toaster that when clicked closes the toaster

**Comment by s4l1h** [comment]
You can do that with **Font Awesome**  just  add the css code below to your project.


```css
  .toast:after{
    position: absolute;
    right:4px;
    top:1px;
    font-family: "Font Awesome 5 Free";
    content: "\f410";
  }
```

https://fontawesome.com/icons/
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css
